/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EnhancedIdentity {
  export type VerifiedIdentityStruct = {
    ssnHash: BytesLike;
    deviceIdHash: BytesLike;
    faceHash: BytesLike;
    combinedHash: BytesLike;
    verifiedAt: BigNumberish;
    isActive: boolean;
    factorsVerified: BigNumberish;
  };

  export type VerifiedIdentityStructOutput = [
    ssnHash: string,
    deviceIdHash: string,
    faceHash: string,
    combinedHash: string,
    verifiedAt: bigint,
    isActive: boolean,
    factorsVerified: bigint
  ] & {
    ssnHash: string;
    deviceIdHash: string;
    faceHash: string;
    combinedHash: string;
    verifiedAt: bigint;
    isActive: boolean;
    factorsVerified: bigint;
  };
}

export interface EnhancedIdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateMyIdentity"
      | "getIdentity"
      | "getRegisteredAddresses"
      | "getRegisteredCount"
      | "identities"
      | "isVerified"
      | "isVerifiedWithFactors"
      | "owner"
      | "registerIdentity"
      | "registerIdentityFor"
      | "registeredAddresses"
      | "revokeIdentity"
      | "transferOwnership"
      | "usedCombinedHashes"
      | "usedSsnHashes"
      | "verifyCombinedHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IdentityRegistered"
      | "IdentityRevoked"
      | "IdentityUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateMyIdentity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedWithFactors",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIdentityFor",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedCombinedHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedSsnHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCombinedHash",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateMyIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identities", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedWithFactors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentityFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedCombinedHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedSsnHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCombinedHash",
    data: BytesLike
  ): Result;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    combinedHash: BytesLike,
    factorsVerified: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    combinedHash: string,
    factorsVerified: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    combinedHash: string;
    factorsVerified: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRevokedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    newCombinedHash: BytesLike,
    newFactorsVerified: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    newCombinedHash: string,
    newFactorsVerified: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    newCombinedHash: string;
    newFactorsVerified: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnhancedIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): EnhancedIdentity;
  waitForDeployment(): Promise<this>;

  interface: EnhancedIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateMyIdentity: TypedContractMethod<[], [void], "nonpayable">;

  getIdentity: TypedContractMethod<
    [_user: AddressLike],
    [EnhancedIdentity.VerifiedIdentityStructOutput],
    "view"
  >;

  getRegisteredAddresses: TypedContractMethod<[], [string[]], "view">;

  getRegisteredCount: TypedContractMethod<[], [bigint], "view">;

  identities: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, bigint, boolean, bigint] & {
        ssnHash: string;
        deviceIdHash: string;
        faceHash: string;
        combinedHash: string;
        verifiedAt: bigint;
        isActive: boolean;
        factorsVerified: bigint;
      }
    ],
    "view"
  >;

  isVerified: TypedContractMethod<[_user: AddressLike], [boolean], "view">;

  isVerifiedWithFactors: TypedContractMethod<
    [_user: AddressLike, _minFactors: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerIdentity: TypedContractMethod<
    [
      _ssnHash: BytesLike,
      _deviceIdHash: BytesLike,
      _faceHash: BytesLike,
      _combinedHash: BytesLike,
      _factorsVerified: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerIdentityFor: TypedContractMethod<
    [
      _user: AddressLike,
      _ssnHash: BytesLike,
      _deviceIdHash: BytesLike,
      _faceHash: BytesLike,
      _combinedHash: BytesLike,
      _factorsVerified: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registeredAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  revokeIdentity: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedCombinedHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  usedSsnHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyCombinedHash: TypedContractMethod<
    [_user: AddressLike, _combinedHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateMyIdentity"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getIdentity"
  ): TypedContractMethod<
    [_user: AddressLike],
    [EnhancedIdentity.VerifiedIdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRegisteredCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "identities"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, bigint, boolean, bigint] & {
        ssnHash: string;
        deviceIdHash: string;
        faceHash: string;
        combinedHash: string;
        verifiedAt: bigint;
        isActive: boolean;
        factorsVerified: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerifiedWithFactors"
  ): TypedContractMethod<
    [_user: AddressLike, _minFactors: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<
    [
      _ssnHash: BytesLike,
      _deviceIdHash: BytesLike,
      _faceHash: BytesLike,
      _combinedHash: BytesLike,
      _factorsVerified: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerIdentityFor"
  ): TypedContractMethod<
    [
      _user: AddressLike,
      _ssnHash: BytesLike,
      _deviceIdHash: BytesLike,
      _faceHash: BytesLike,
      _combinedHash: BytesLike,
      _factorsVerified: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "revokeIdentity"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedCombinedHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedSsnHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyCombinedHash"
  ): TypedContractMethod<
    [_user: AddressLike, _combinedHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRevoked"
  ): TypedContractEvent<
    IdentityRevokedEvent.InputTuple,
    IdentityRevokedEvent.OutputTuple,
    IdentityRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUpdated"
  ): TypedContractEvent<
    IdentityUpdatedEvent.InputTuple,
    IdentityUpdatedEvent.OutputTuple,
    IdentityUpdatedEvent.OutputObject
  >;

  filters: {
    "IdentityRegistered(address,bytes32,uint8,uint256)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityRevoked(address,uint256)": TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;
    IdentityRevoked: TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;

    "IdentityUpdated(address,bytes32,uint8,uint256)": TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
    IdentityUpdated: TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
  };
}
