/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Voting {
  export type ProposalStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    voteCount: BigNumberish;
    ipfsHash: string;
  };

  export type ProposalStructOutput = [
    id: bigint,
    name: string,
    description: string,
    voteCount: bigint,
    ipfsHash: string
  ] & {
    id: bigint;
    name: string;
    description: string;
    voteCount: bigint;
    ipfsHash: string;
  };
}

export interface VotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addProposal"
      | "authorizeVoter"
      | "endVoting"
      | "getProposal"
      | "getProposals"
      | "getProposalsCount"
      | "getResults"
      | "hasVoted"
      | "isAuthorized"
      | "owner"
      | "proposals"
      | "startTime"
      | "startVoting"
      | "timeRemaining"
      | "totalVotes"
      | "vote"
      | "voters"
      | "votingActive"
      | "votingDuration"
      | "votingTitle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProposalAdded"
      | "VoteCast"
      | "VoterAuthorized"
      | "VotingEnded"
      | "VotingStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addProposal",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "endVoting", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startVoting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeRemaining",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "voters", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "votingActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingTitle",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endVoting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingTitle",
    data: BytesLike
  ): Result;
}

export namespace ProposalAddedEvent {
  export type InputTuple = [proposalId: BigNumberish, name: string];
  export type OutputTuple = [proposalId: bigint, name: string];
  export interface OutputObject {
    proposalId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [voter: AddressLike, proposalId: BigNumberish];
  export type OutputTuple = [voter: string, proposalId: bigint];
  export interface OutputObject {
    voter: string;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterAuthorizedEvent {
  export type InputTuple = [voter: AddressLike];
  export type OutputTuple = [voter: string];
  export interface OutputObject {
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingEndedEvent {
  export type InputTuple = [endTime: BigNumberish, totalVotes: BigNumberish];
  export type OutputTuple = [endTime: bigint, totalVotes: bigint];
  export interface OutputObject {
    endTime: bigint;
    totalVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingStartedEvent {
  export type InputTuple = [startTime: BigNumberish, duration: BigNumberish];
  export type OutputTuple = [startTime: bigint, duration: bigint];
  export interface OutputObject {
    startTime: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Voting extends BaseContract {
  connect(runner?: ContractRunner | null): Voting;
  waitForDeployment(): Promise<this>;

  interface: VotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addProposal: TypedContractMethod<
    [_name: string, _description: string, _ipfsHash: string],
    [void],
    "nonpayable"
  >;

  authorizeVoter: TypedContractMethod<
    [_voter: AddressLike],
    [void],
    "nonpayable"
  >;

  endVoting: TypedContractMethod<[], [void], "nonpayable">;

  getProposal: TypedContractMethod<
    [_id: BigNumberish],
    [Voting.ProposalStructOutput],
    "view"
  >;

  getProposals: TypedContractMethod<
    [],
    [Voting.ProposalStructOutput[]],
    "view"
  >;

  getProposalsCount: TypedContractMethod<[], [bigint], "view">;

  getResults: TypedContractMethod<[], [bigint[]], "view">;

  hasVoted: TypedContractMethod<[_voter: AddressLike], [boolean], "view">;

  isAuthorized: TypedContractMethod<[_voter: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string] & {
        id: bigint;
        name: string;
        description: string;
        voteCount: bigint;
        ipfsHash: string;
      }
    ],
    "view"
  >;

  startTime: TypedContractMethod<[], [bigint], "view">;

  startVoting: TypedContractMethod<[], [void], "nonpayable">;

  timeRemaining: TypedContractMethod<[], [bigint], "view">;

  totalVotes: TypedContractMethod<[], [bigint], "view">;

  vote: TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;

  voters: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint] & {
        authorized: boolean;
        voted: boolean;
        vote: bigint;
      }
    ],
    "view"
  >;

  votingActive: TypedContractMethod<[], [boolean], "view">;

  votingDuration: TypedContractMethod<[], [bigint], "view">;

  votingTitle: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addProposal"
  ): TypedContractMethod<
    [_name: string, _description: string, _ipfsHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeVoter"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "endVoting"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [Voting.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposals"
  ): TypedContractMethod<[], [Voting.ProposalStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProposalsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResults"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[_voter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<[_voter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string] & {
        id: bigint;
        name: string;
        description: string;
        voteCount: bigint;
        ipfsHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startVoting"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeRemaining"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint] & {
        authorized: boolean;
        voted: boolean;
        vote: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votingActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "votingDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "votingTitle"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProposalAdded"
  ): TypedContractEvent<
    ProposalAddedEvent.InputTuple,
    ProposalAddedEvent.OutputTuple,
    ProposalAddedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoterAuthorized"
  ): TypedContractEvent<
    VoterAuthorizedEvent.InputTuple,
    VoterAuthorizedEvent.OutputTuple,
    VoterAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "VotingEnded"
  ): TypedContractEvent<
    VotingEndedEvent.InputTuple,
    VotingEndedEvent.OutputTuple,
    VotingEndedEvent.OutputObject
  >;
  getEvent(
    key: "VotingStarted"
  ): TypedContractEvent<
    VotingStartedEvent.InputTuple,
    VotingStartedEvent.OutputTuple,
    VotingStartedEvent.OutputObject
  >;

  filters: {
    "ProposalAdded(uint256,string)": TypedContractEvent<
      ProposalAddedEvent.InputTuple,
      ProposalAddedEvent.OutputTuple,
      ProposalAddedEvent.OutputObject
    >;
    ProposalAdded: TypedContractEvent<
      ProposalAddedEvent.InputTuple,
      ProposalAddedEvent.OutputTuple,
      ProposalAddedEvent.OutputObject
    >;

    "VoteCast(address,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoterAuthorized(address)": TypedContractEvent<
      VoterAuthorizedEvent.InputTuple,
      VoterAuthorizedEvent.OutputTuple,
      VoterAuthorizedEvent.OutputObject
    >;
    VoterAuthorized: TypedContractEvent<
      VoterAuthorizedEvent.InputTuple,
      VoterAuthorizedEvent.OutputTuple,
      VoterAuthorizedEvent.OutputObject
    >;

    "VotingEnded(uint256,uint256)": TypedContractEvent<
      VotingEndedEvent.InputTuple,
      VotingEndedEvent.OutputTuple,
      VotingEndedEvent.OutputObject
    >;
    VotingEnded: TypedContractEvent<
      VotingEndedEvent.InputTuple,
      VotingEndedEvent.OutputTuple,
      VotingEndedEvent.OutputObject
    >;

    "VotingStarted(uint256,uint256)": TypedContractEvent<
      VotingStartedEvent.InputTuple,
      VotingStartedEvent.OutputTuple,
      VotingStartedEvent.OutputObject
    >;
    VotingStarted: TypedContractEvent<
      VotingStartedEvent.InputTuple,
      VotingStartedEvent.OutputTuple,
      VotingStartedEvent.OutputObject
    >;
  };
}
