/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Voting {
  export type VerifiedVoterStruct = {
    walletAddress: AddressLike;
    idHash: string;
    name: string;
    idType: string;
    verifiedAt: BigNumberish;
    isVerified: boolean;
  };

  export type VerifiedVoterStructOutput = [
    walletAddress: string,
    idHash: string,
    name: string,
    idType: string,
    verifiedAt: bigint,
    isVerified: boolean
  ] & {
    walletAddress: string;
    idHash: string;
    name: string;
    idType: string;
    verifiedAt: bigint;
    isVerified: boolean;
  };

  export type ProposalStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    ipfsHash: string;
    totalVotes: BigNumberish;
    optionsCount: BigNumberish;
    creator: AddressLike;
    startTime: BigNumberish;
    duration: BigNumberish;
    votingActive: boolean;
  };

  export type ProposalStructOutput = [
    id: bigint,
    name: string,
    description: string,
    ipfsHash: string,
    totalVotes: bigint,
    optionsCount: bigint,
    creator: string,
    startTime: bigint,
    duration: bigint,
    votingActive: boolean
  ] & {
    id: bigint;
    name: string;
    description: string;
    ipfsHash: string;
    totalVotes: bigint;
    optionsCount: bigint;
    creator: string;
    startTime: bigint;
    duration: bigint;
    votingActive: boolean;
  };

  export type VotingOptionStruct = {
    id: BigNumberish;
    name: string;
    voteCount: BigNumberish;
  };

  export type VotingOptionStructOutput = [
    id: bigint,
    name: string,
    voteCount: bigint
  ] & { id: bigint; name: string; voteCount: bigint };
}

export interface VotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addForAgainstOptions"
      | "addProposal"
      | "addVotingOption"
      | "authorizeVoter"
      | "endVoting"
      | "getAllVerifiedVoters"
      | "getProposal"
      | "getProposalOption"
      | "getProposalOptions"
      | "getProposalResults"
      | "getProposals"
      | "getProposalsCount"
      | "getResults"
      | "getVerifiedVoter"
      | "getVerifiedVoterAddresses"
      | "getVerifiedVoterCount"
      | "getVoterChoice"
      | "hasVoted"
      | "hasVotedOnProposal"
      | "isAuthorizedForProposal"
      | "isProposalVotingActive"
      | "isVoterVerified"
      | "owner"
      | "proposalOptions"
      | "proposalVoted"
      | "proposals"
      | "registerVerifiedVoter"
      | "startVoting"
      | "timeRemaining"
      | "totalVotes"
      | "usedIdHashes"
      | "verifiedVoterAddresses"
      | "verifiedVoters"
      | "vote"
      | "voterProposalAuthorization"
      | "voters"
      | "votingTitle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProposalAdded"
      | "VoteCast"
      | "VoterAuthorized"
      | "VoterIdentityRegistered"
      | "VotingEnded"
      | "VotingOptionAdded"
      | "VotingStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addForAgainstOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addProposal",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addVotingOption",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeVoter",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endVoting",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVerifiedVoters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalOption",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedVoterAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedVoterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterChoice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotedOnProposal",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedForProposal",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProposalVotingActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVoterVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalOptions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalVoted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVerifiedVoter",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "startVoting",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedIdHashes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedVoterAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedVoters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voterProposalAuthorization",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "voters", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "votingTitle",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addForAgainstOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addVotingOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endVoting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllVerifiedVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedVoterAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedVoterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasVotedOnProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedForProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProposalVotingActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVoterVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVerifiedVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usedIdHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedVoterAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voterProposalAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingTitle",
    data: BytesLike
  ): Result;
}

export namespace ProposalAddedEvent {
  export type InputTuple = [proposalId: BigNumberish, name: string];
  export type OutputTuple = [proposalId: bigint, name: string];
  export interface OutputObject {
    proposalId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    voter: AddressLike,
    proposalId: BigNumberish,
    optionId: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    proposalId: bigint,
    optionId: bigint
  ];
  export interface OutputObject {
    voter: string;
    proposalId: bigint;
    optionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterAuthorizedEvent {
  export type InputTuple = [voter: AddressLike, proposalId: BigNumberish];
  export type OutputTuple = [voter: string, proposalId: bigint];
  export interface OutputObject {
    voter: string;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterIdentityRegisteredEvent {
  export type InputTuple = [
    voter: AddressLike,
    name: string,
    idType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    name: string,
    idType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    voter: string;
    name: string;
    idType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingEndedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    endTime: BigNumberish,
    proposalTotalVotes: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    endTime: bigint,
    proposalTotalVotes: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    endTime: bigint;
    proposalTotalVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingOptionAddedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    optionId: BigNumberish,
    optionName: string
  ];
  export type OutputTuple = [
    proposalId: bigint,
    optionId: bigint,
    optionName: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    optionId: bigint;
    optionName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingStartedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    startTime: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    startTime: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    startTime: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Voting extends BaseContract {
  connect(runner?: ContractRunner | null): Voting;
  waitForDeployment(): Promise<this>;

  interface: VotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addForAgainstOptions: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addProposal: TypedContractMethod<
    [_name: string, _description: string, _ipfsHash: string],
    [void],
    "nonpayable"
  >;

  addVotingOption: TypedContractMethod<
    [_proposalId: BigNumberish, _optionName: string],
    [void],
    "nonpayable"
  >;

  authorizeVoter: TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  endVoting: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllVerifiedVoters: TypedContractMethod<
    [],
    [Voting.VerifiedVoterStructOutput[]],
    "view"
  >;

  getProposal: TypedContractMethod<
    [_id: BigNumberish],
    [Voting.ProposalStructOutput],
    "view"
  >;

  getProposalOption: TypedContractMethod<
    [_proposalId: BigNumberish, _optionId: BigNumberish],
    [Voting.VotingOptionStructOutput],
    "view"
  >;

  getProposalOptions: TypedContractMethod<
    [_proposalId: BigNumberish],
    [Voting.VotingOptionStructOutput[]],
    "view"
  >;

  getProposalResults: TypedContractMethod<
    [_proposalId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getProposals: TypedContractMethod<
    [],
    [Voting.ProposalStructOutput[]],
    "view"
  >;

  getProposalsCount: TypedContractMethod<[], [bigint], "view">;

  getResults: TypedContractMethod<[], [bigint[]], "view">;

  getVerifiedVoter: TypedContractMethod<
    [_voter: AddressLike],
    [Voting.VerifiedVoterStructOutput],
    "view"
  >;

  getVerifiedVoterAddresses: TypedContractMethod<[], [string[]], "view">;

  getVerifiedVoterCount: TypedContractMethod<[], [bigint], "view">;

  getVoterChoice: TypedContractMethod<
    [_voter: AddressLike],
    [
      [bigint, bigint, boolean] & {
        proposalId: bigint;
        optionId: bigint;
        voted: boolean;
      }
    ],
    "view"
  >;

  hasVoted: TypedContractMethod<[_voter: AddressLike], [boolean], "view">;

  hasVotedOnProposal: TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  isAuthorizedForProposal: TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  isProposalVotingActive: TypedContractMethod<
    [_proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  isVoterVerified: TypedContractMethod<
    [_voter: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposalOptions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint] & { id: bigint; name: string; voteCount: bigint }
    ],
    "view"
  >;

  proposalVoted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        description: string;
        ipfsHash: string;
        totalVotes: bigint;
        optionsCount: bigint;
        creator: string;
        startTime: bigint;
        duration: bigint;
        votingActive: boolean;
      }
    ],
    "view"
  >;

  registerVerifiedVoter: TypedContractMethod<
    [_idHash: string, _name: string, _idType: string],
    [void],
    "nonpayable"
  >;

  startVoting: TypedContractMethod<
    [_proposalId: BigNumberish, _durationInMinutes: BigNumberish],
    [void],
    "nonpayable"
  >;

  timeRemaining: TypedContractMethod<
    [_proposalId: BigNumberish],
    [bigint],
    "view"
  >;

  totalVotes: TypedContractMethod<[], [bigint], "view">;

  usedIdHashes: TypedContractMethod<[arg0: string], [boolean], "view">;

  verifiedVoterAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  verifiedVoters: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, bigint, boolean] & {
        walletAddress: string;
        idHash: string;
        name: string;
        idType: string;
        verifiedAt: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  vote: TypedContractMethod<
    [_proposalId: BigNumberish, _optionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  voterProposalAuthorization: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  voters: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint] & {
        voted: boolean;
        votedProposalId: bigint;
        votedOptionId: bigint;
      }
    ],
    "view"
  >;

  votingTitle: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addForAgainstOptions"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addProposal"
  ): TypedContractMethod<
    [_name: string, _description: string, _ipfsHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addVotingOption"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _optionName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeVoter"
  ): TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endVoting"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllVerifiedVoters"
  ): TypedContractMethod<[], [Voting.VerifiedVoterStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [Voting.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalOption"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _optionId: BigNumberish],
    [Voting.VotingOptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalOptions"
  ): TypedContractMethod<
    [_proposalId: BigNumberish],
    [Voting.VotingOptionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalResults"
  ): TypedContractMethod<[_proposalId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProposals"
  ): TypedContractMethod<[], [Voting.ProposalStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProposalsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResults"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVerifiedVoter"
  ): TypedContractMethod<
    [_voter: AddressLike],
    [Voting.VerifiedVoterStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifiedVoterAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVerifiedVoterCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoterChoice"
  ): TypedContractMethod<
    [_voter: AddressLike],
    [
      [bigint, bigint, boolean] & {
        proposalId: bigint;
        optionId: bigint;
        voted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[_voter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasVotedOnProposal"
  ): TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedForProposal"
  ): TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProposalVotingActive"
  ): TypedContractMethod<[_proposalId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVoterVerified"
  ): TypedContractMethod<[_voter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalOptions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint] & { id: bigint; name: string; voteCount: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalVoted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        description: string;
        ipfsHash: string;
        totalVotes: bigint;
        optionsCount: bigint;
        creator: string;
        startTime: bigint;
        duration: bigint;
        votingActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerVerifiedVoter"
  ): TypedContractMethod<
    [_idHash: string, _name: string, _idType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startVoting"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _durationInMinutes: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeRemaining"
  ): TypedContractMethod<[_proposalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usedIdHashes"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifiedVoterAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verifiedVoters"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, bigint, boolean] & {
        walletAddress: string;
        idHash: string;
        name: string;
        idType: string;
        verifiedAt: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _optionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voterProposalAuthorization"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint] & {
        voted: boolean;
        votedProposalId: bigint;
        votedOptionId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votingTitle"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProposalAdded"
  ): TypedContractEvent<
    ProposalAddedEvent.InputTuple,
    ProposalAddedEvent.OutputTuple,
    ProposalAddedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoterAuthorized"
  ): TypedContractEvent<
    VoterAuthorizedEvent.InputTuple,
    VoterAuthorizedEvent.OutputTuple,
    VoterAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "VoterIdentityRegistered"
  ): TypedContractEvent<
    VoterIdentityRegisteredEvent.InputTuple,
    VoterIdentityRegisteredEvent.OutputTuple,
    VoterIdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VotingEnded"
  ): TypedContractEvent<
    VotingEndedEvent.InputTuple,
    VotingEndedEvent.OutputTuple,
    VotingEndedEvent.OutputObject
  >;
  getEvent(
    key: "VotingOptionAdded"
  ): TypedContractEvent<
    VotingOptionAddedEvent.InputTuple,
    VotingOptionAddedEvent.OutputTuple,
    VotingOptionAddedEvent.OutputObject
  >;
  getEvent(
    key: "VotingStarted"
  ): TypedContractEvent<
    VotingStartedEvent.InputTuple,
    VotingStartedEvent.OutputTuple,
    VotingStartedEvent.OutputObject
  >;

  filters: {
    "ProposalAdded(uint256,string)": TypedContractEvent<
      ProposalAddedEvent.InputTuple,
      ProposalAddedEvent.OutputTuple,
      ProposalAddedEvent.OutputObject
    >;
    ProposalAdded: TypedContractEvent<
      ProposalAddedEvent.InputTuple,
      ProposalAddedEvent.OutputTuple,
      ProposalAddedEvent.OutputObject
    >;

    "VoteCast(address,uint256,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoterAuthorized(address,uint256)": TypedContractEvent<
      VoterAuthorizedEvent.InputTuple,
      VoterAuthorizedEvent.OutputTuple,
      VoterAuthorizedEvent.OutputObject
    >;
    VoterAuthorized: TypedContractEvent<
      VoterAuthorizedEvent.InputTuple,
      VoterAuthorizedEvent.OutputTuple,
      VoterAuthorizedEvent.OutputObject
    >;

    "VoterIdentityRegistered(address,string,string,uint256)": TypedContractEvent<
      VoterIdentityRegisteredEvent.InputTuple,
      VoterIdentityRegisteredEvent.OutputTuple,
      VoterIdentityRegisteredEvent.OutputObject
    >;
    VoterIdentityRegistered: TypedContractEvent<
      VoterIdentityRegisteredEvent.InputTuple,
      VoterIdentityRegisteredEvent.OutputTuple,
      VoterIdentityRegisteredEvent.OutputObject
    >;

    "VotingEnded(uint256,uint256,uint256)": TypedContractEvent<
      VotingEndedEvent.InputTuple,
      VotingEndedEvent.OutputTuple,
      VotingEndedEvent.OutputObject
    >;
    VotingEnded: TypedContractEvent<
      VotingEndedEvent.InputTuple,
      VotingEndedEvent.OutputTuple,
      VotingEndedEvent.OutputObject
    >;

    "VotingOptionAdded(uint256,uint256,string)": TypedContractEvent<
      VotingOptionAddedEvent.InputTuple,
      VotingOptionAddedEvent.OutputTuple,
      VotingOptionAddedEvent.OutputObject
    >;
    VotingOptionAdded: TypedContractEvent<
      VotingOptionAddedEvent.InputTuple,
      VotingOptionAddedEvent.OutputTuple,
      VotingOptionAddedEvent.OutputObject
    >;

    "VotingStarted(uint256,uint256,uint256)": TypedContractEvent<
      VotingStartedEvent.InputTuple,
      VotingStartedEvent.OutputTuple,
      VotingStartedEvent.OutputObject
    >;
    VotingStarted: TypedContractEvent<
      VotingStartedEvent.InputTuple,
      VotingStartedEvent.OutputTuple,
      VotingStartedEvent.OutputObject
    >;
  };
}
